### ISSUE TITLE
JsonFieldConvertor在转换复杂List带泛型时会出现问题

### ISSUE THREAD

**Issue by duanshuo198802** [troyzhxu/bean-searcher#99]
JsonFieldConvertor在转换复杂List带泛型时会出现问题

## 问题出现版本
4.3.0

## 问题详情

字段配置
```
    @Column(typeHandler = JacksonTypeHandler::class)
    @DbField(type = DbType.JSON)
    var dataInfo: List<LabelValueDTO<String>>? = null
```
其中LabelValueDTO
```
data class LabelValueDTO<T>(var value: T,var label: String,var children: List<LabelValueDTO<T>>?)
```
查询时出现错误，主要报错信息如下
```
Caused by: java.lang.ClassCastException: class sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl cannot be cast to class java.lang.Class (sun.reflect.generics.reflectiveObjects.ParameterizedTypeImpl and java.lang.Class are in module java.base of loader 'bootstrap')
	at cn.zhxu.bs.convertor.JsonFieldConvertor.doConvert(JsonFieldConvertor.java:84)
	at cn.zhxu.bs.convertor.JsonFieldConvertor.convert(JsonFieldConvertor.java:51)
	at cn.zhxu.bs.implement.DefaultBeanReflector.convert(DefaultBeanReflector.java:65)
	at cn.zhxu.bs.implement.DefaultBeanReflector.reflect(DefaultBeanReflector.java:36)
	... 45 common frames omitted
```
将LabelValueDTO替换为LabelValueStringDTO时，就不会报错，LabelValueStringDTO如下
```
data class LabelValueStringDTO(var value: String,var label: String,var children: List<LabelValueDTO<String>>?)
```
问题应该出现在List对象中出现了泛型，使用java开发不知道会不会遇见这样的情况，目前我用的kotlin开发出现了这样的情况。

**Comment by troyzhxu** [comment]
感谢反馈，确实是一个 BUG，将在下一个版本修复

**Comment by troyzhxu** [comment]
已在 `v4.3.1` 中修复：https://github.com/troyzhxu/bean-searcher/releases/tag/v4.3.1
